[project]
name = ""
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "pyyaml",
    "requests",
    "plotnine",
    "bs4",
    "lxml",
    "requests-cache",
    "requests-ratelimiter",
    "pyrate-limiter",
    "xlrd",
    "beautifulsoup4",
    "altair[all]",
    "scikit-learn",
    "nbconvert",
    "pandas",
    "openbb>=4.7.2",
    "quantlib>=1.42.1",
]

[dependency-groups]
dev = [
    "pytest",
    "ipykernel",
    "waybackpack",
    "requests-html",
    "yfinance",
    "alpha-vantage",
    "fredapi>=0.5.2",
    "yfinance-cache>=0.7.13",
    "openbb>=4.7.2",
    "openbb-alpha-vantage>=1.6.1",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
